// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: users.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, created_at, updated_at, email, hashed_password)
VALUES (gen_random_uuid(), NOW(), NOW(), $1, $2)
RETURNING id, created_at, updated_at, email, hashed_password, is_chirpy_red
`

type CreateUserParams struct {
	Email          string
	HashedPassword string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Email, arg.HashedPassword)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.HashedPassword,
		&i.IsChirpyRed,
	)
	return i, err
}

const deleteUsers = `-- name: DeleteUsers :exec
DELETE FROM users
`

func (q *Queries) DeleteUsers(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteUsers)
	return err
}

const lookupUser = `-- name: LookupUser :one
SELECT id, created_at, updated_at, email, hashed_password, is_chirpy_red
FROM users
WHERE email = $1
`

func (q *Queries) LookupUser(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, lookupUser, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.HashedPassword,
		&i.IsChirpyRed,
	)
	return i, err
}

const makeUserRed = `-- name: MakeUserRed :one
UPDATE users 
SET is_chirpy_red = true
WHERE id = $1
RETURNING id, is_chirpy_red
`

type MakeUserRedRow struct {
	ID          uuid.UUID
	IsChirpyRed sql.NullBool
}

func (q *Queries) MakeUserRed(ctx context.Context, id uuid.UUID) (MakeUserRedRow, error) {
	row := q.db.QueryRowContext(ctx, makeUserRed, id)
	var i MakeUserRedRow
	err := row.Scan(&i.ID, &i.IsChirpyRed)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :one
UPDATE users
SET email = $1, hashed_password = $2
WHERE id = $3
RETURNING id, email, created_at, is_chirpy_red
`

type UpdateUserPasswordParams struct {
	Email          string
	HashedPassword string
	ID             uuid.UUID
}

type UpdateUserPasswordRow struct {
	ID          uuid.UUID
	Email       string
	CreatedAt   time.Time
	IsChirpyRed sql.NullBool
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (UpdateUserPasswordRow, error) {
	row := q.db.QueryRowContext(ctx, updateUserPassword, arg.Email, arg.HashedPassword, arg.ID)
	var i UpdateUserPasswordRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CreatedAt,
		&i.IsChirpyRed,
	)
	return i, err
}
